<a href="https://colab.research.google.com/github/Valentianets/Analitic/blob/main/Numpy_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Создайте массив из 10 нулей
import numpy as np
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Создать массив из 10 единиц
import numpy as np
array=np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# Создать массив из 10 пятерок
import numpy as np
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
# Создать массив из целых чисел от 10 до 50
import numpy as np
array=np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Создать массив из четных чисел от 10 до 50
import numpy as np
array=np.arange(10,50,2)
print(array) 

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
# Создать матрицу 3х3 с числами от 0 до 8
import numpy as np
Z = np.arange(9).reshape (3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Создать единичную матрицу 3x3
import numpy as np
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Используйте NumPy для генерации случайного числа от 0 до 1
import numpy as np
rand_num = np.random.normal(0,1,1)
print(rand_num)

[-1.20265368]


In [ ]:
#Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
import numpy as np
rand_num = np.random.normal(0,1,25)
print(rand_num)

[ 1.19902808  1.27383194 -0.81887991 -1.11064746  0.68212141 -0.31378817
  0.97904458 -2.28251258  0.33835746 -0.52672231  2.18683345 -0.71238515
  0.84138397 -0.97744072 -0.78116683 -0.62636285 -0.6548343  -0.43867782
  0.69559747 -0.80872448  1.27184559  0.85788763 -0.42865785 -0.52574023
 -0.02540327]


In [ ]:
#Создайте следующую матрицу используя функции библиотеки NumPy:
import numpy as np
z = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
print (z)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [6]:
#Необходимо написать код который вернет следующую матрицу из стартовой
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat[2:,1:])



[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [7]:
#код обращения к элементу который вернет значение 20 из стартовой матрицы задачи l
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat[3,4])

20


In [8]:
# код к стартовой матрице задачи l, который воспроизводит вывод, показанный ниже
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat[0:3,1:2])

[[ 2]
 [ 7]
 [12]]


In [9]:
# код к стартовой матрице задачи l, который воспроизводит вывод, показанный ниже
print(mat[4:])

[[21 22 23 24 25]]


In [10]:
# код к стартовой матрице задачи l, который воспроизводитвывод, показанный ниже
print(mat[3:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [11]:
# Получить сумму всех значений в стартовой матрице mat
print(np.sum(mat))

325


In [12]:
# Получить стандартное отклонение в стартовой матрице mat
print(np.std(mat))

7.211102550927978


In [13]:
#Получить сумму значений в колонках в стартовой матрице mat
print(np.sum(mat, axis = 0))

[55 60 65 70 75]
